### PR TITLE
Add podcast tracking

### PR DESCRIPTION
**Pull request by mchv**
We add a special parameter that will be used to identify amazon echo as a platform in ophan.
@oilnam

### CODE REVIEW

**Comment by tomrf1** [comment]
👍

**Comment by oilnam** [comment]
I want to see a real log of this working or I won't believe it 😆

**Comment by mchv** [comment]
@oilnam

initial test with my browser
```
2017-02-01T15:25:00.000-4pWnyRo-zt5Re4QAAAAA.log:<134>2017-02-01T15:27:05Z cache-lcy1131 audio-logging[130012]: "" "Wed, 01 Feb 2017 15:27:05 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "206" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "(null)" "bytes=511294-81369182" "567" "0" "audio/mp3" "16" "GB" "H9" "London" "(null)"
2017-02-01T15:25:00.000-BXHuJA_8SatxS8cAAAAA.log:<134>2017-02-01T15:27:46Z cache-lcy1133 audio-logging[172546]: "" "Wed, 01 Feb 2017 15:27:45 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "206" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "https://audio.guim.co.uk/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "bytes=22216704-" "620" "0" "audio/mp3" "57" "GB" "H9" "London" "(null)"
2017-02-01T15:25:00.000-FsZdPtHPtdmZQ9EAAAAA.log:<134>2017-02-01T15:27:05Z cache-lcy1131 audio-logging[508271]: "" "Wed, 01 Feb 2017 15:27:05 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "206" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "(null)" "bytes=511294-511294" "565" "0" "audio/mp3" "16" "GB" "H9" "London" "(null)"
2017-02-01T15:25:00.000-Y73Td9st4oSrI0MAAAAA.log:<134>2017-02-01T15:26:50Z cache-lcy1129 audio-logging[218999]: "" "Wed, 01 Feb 2017 15:26:50 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "200" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "(null)" "(null)" "534" "0" "audio/mp3" "(null)" "GB" "H9" "London" "(null)"
2017-02-01T15:25:00.000-aM4tFepu0JnJJAgAAAAA.log:<134>2017-02-01T15:27:43Z cache-lcy1138 audio-logging[14817]: "" "Wed, 01 Feb 2017 15:27:42 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "206" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "https://audio.guim.co.uk/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "bytes=163840-" "618" "0" "audio/mp3" "54" "GB" "H9" "London" "(null)"
2017-02-01T15:25:00.000-rUOLTTWZ4qyphlUAAAAA.log:<134>2017-02-01T15:26:51Z cache-lcy1131 audio-logging[438579]: "" "Wed, 01 Feb 2017 15:26:50 GMT" "GET" "/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "206" "77.91.250.236" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" "https://audio.guim.co.uk/2017/01/30-62485-gnl.sci.20170201.ms.cross_section_uta_firth.mp3?platform=amazon-echo" "bytes=0-" "567" "0" "audio/mp3" "2" "GB" "H9" "London" "(null)"
```

The echo device
```
2017-02-01T17:05:00.000-Is6loK38u7U3R2wAAAAA.log:<134>2017-02-01T17:06:12Z cache-lhr6339 audio-logging[136689]: "" "Wed, 01 Feb 2017 17:06:11 GMT" "GET" "/2017/01/30-61869-gu.foo.ps.170130.suttonutd.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "200" "81.149.104.153" "(null)" "(null)" "(null)" "140" "0" "audio/mp3" "(null)" "GB" "(null)" "(null)" "(null)"
2017-02-01T17:05:00.000-kuVU43yIhEHvRo4AAAAA.log:<134>2017-02-01T17:06:11Z cache-lcy1120 audio-logging[173347]: "" "Wed, 01 Feb 2017 17:06:11 GMT" "GET" "/2017/01/30-61869-gu.foo.ps.170130.suttonutd.mp3?platform=amazon-echo" "composer-uploads-audio.s3-website-eu-west-1.amazonaws.com" "200" "185.31.19.21" "(null)" "(null)" "(null)" "656" "0" "audio/mp3" "(null)" "EU" "(null)" "(null)" "(null)"
```

**Comment by mchv** [comment]
we will probably have to see more traffic to see how reliable it is

**Comment by oilnam** [comment]
💯

**Pull request merged**
